# https://taskfile.dev

version: "3"

tasks:
  publish:
    vars:
      DOCKER_IMAGE: ghcr.io/platformplane/toolkit

    cmds:
      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}} ../ -f Dockerfile
